language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra-android-support
    - extra-android-m2repository

before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'cmake;3.6.4111459'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: ./gradlew clean assembleDebug
